// Embeds the built browser SDK into the worker as a string module, so the
// platform serves /__quick.js with no extra fetch or asset pipeline.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const sdkPath = join(here, '..', '..', 'sdk', 'dist', 'quick.js');
const outDir = join(here, '..', 'src', 'generated');

if (!existsSync(sdkPath)) {
  console.error(`SDK bundle not found at ${sdkPath} – run \`pnpm --filter @openquick/sdk build\` first.`);
  process.exit(1);
}

const source = readFileSync(sdkPath, 'utf8');
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, 'sdk.ts'),
  `// Generated by scripts/embed-sdk.mjs – do not edit.\nexport const SDK_SOURCE = ${JSON.stringify(source)};\n`,
);
console.log(`Embedded SDK (${source.length} bytes) into src/generated/sdk.ts`);
